In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

### 1. Create an array with (100) elements using np.arange()

In [2]:
range_array = np.arange(0,101)
range_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

### 2. Create two numpy arrays whose values are neither all 0 or 1. Multiply the two arrays and save the result i.e., result = array1 * array2.

In [25]:
rand_array0 = np.random.random(15)*5
rand_array1 = np.random.random(15)*4
rand_dict = {"rand_array0": rand_array0,
            "rand_array1": rand_array1}
rand_df = pd.DataFrame(rand_dict)
rand_df["Product of rand_array0*rand_array1"] = rand_array0 * rand_array1
rand_df

    rand_array0  rand_array1  Product of rand_array0*rand_array1
0      0.471712     3.401899                            1.604717
1      4.946151     3.712011                           18.360169
2      3.085177     2.421125                            7.469598
3      3.123466     3.990061                           12.462820
4      0.396371     0.617582                            0.244792
5      4.468173     2.033894                            9.087790
6      0.178770     2.012052                            0.359694
7      1.017448     1.031648                            1.049648
8      4.277040     3.384560                           14.475898
9      4.440911     0.310396                            1.378443
10     4.254617     2.142080                            9.113732
11     3.541832     0.405334                            1.435626
12     0.668633     0.550756                            0.368254
13     3.349911     0.991050                            3.319931
14     3.004580     2.478941                            7.448177

### 3. Create a dictionary where each key points to a unique numpy array. All arrays should be of the same length. Then transform that dictionary into a pandas dataframe.

In [33]:
unique_dict = {"AAPL Rev(in millions)":{},
              "AAPL Market Cap(in millions)": {},
              "AAPL COGS(in millions)": {},
              }
for key in unique_dict:
    for i in range(2005,2021):
        unique_dict[key][i] = np.random.random()*1000

unique_df = pd.DataFrame(unique_dict)
unique_df["P/S Ratio"] = unique_df["AAPL Market Cap(in millions)"]/unique_df["AAPL Rev(in millions)"]
unique_df

,AAPL Rev(in millions),AAPL Market Cap(in millions),AAPL COGS(in millions),P/S Ratio
2005,51.078242,683.932896,625.782693,13.389907
2006,167.749861,792.078522,736.441629,4.721783
2007,373.092352,97.869161,529.280316,0.262319
2008,292.735962,697.097173,71.783298,2.381317
2009,165.189184,926.670453,357.415049,5.609753
2010,19.233834,915.494909,26.055033,47.598149
2011,270.300461,230.330700,477.687311,0.852128
2012,258.809615,81.400169,896.775218,0.314518
2013,882.830778,988.264260,450.161602,1.119427
2014,520.586228,245.330554,120.709289,0.471258
2015,54.257277,164.001575,51.417659,3.022665
2016,833.107894,448.068819,328.351043,0.537828
2017,958.140663,800.034111,532.770509,0.834986
2018,152.172667,813.236558,975.512806,5.344170
2019,454.287906,835.256180,689.176323,1.838605
2020,791.977737,860.861348,332.413906,1.086977

### 4. Import a data set for your project in pandas. You may use whatever means you prefer to import the data. Print the dataframe.

In [77]:
tsla_inc_stat = pd.read_csv('/Users/jacobradke/Documents/GitHub/jacobradke/Homework Projects/tsla_inc_stat.csv')
tsla_inc_stat_df = pd.DataFrame(tsla_inc_stat)
tsla_inc_stat_df

,Date,TotalRevenue,CostOfRevenue,GrossProfit,OperatingExpense,SellingGeneralAndAdministration,ResearchAndDevelopment,OperatingIncome,NetNonOperatingInterestIncomeExpense,InterestIncomeNonOperating,...,NetIncome,BasicEPS,DilutedEPS,BasicAverageShares,DilutedAverageShares,TotalExpenses,InterestIncome,InterestExpense,NetInterestIncome,EBIT
0,6/30/21,"11,958,000,000","9,074,000,000","2,884,000,000","1,549,000,000","973,000,000","576,000,000","1,335,000,000","-64,000,000","11,000,000",...,"1,142,000,000",1.180,1.020,"971,000,000","1,119,000,000","10,623,000,000","11,000,000","75,000,000","-64,000,000","1,368,000,000"
1,3/31/21,"10,389,000,000","8,174,000,000","2,215,000,000","1,722,000,000","1,056,000,000","666,000,000","493,000,000","-89,000,000","10,000,000",...,"438,000,000",0.460,0.390,"961,000,000","1,133,000,000","9,896,000,000","10,000,000","99,000,000","-89,000,000","632,000,000"
2,12/31/20,"10,744,000,000","8,678,000,000","2,066,000,000","1,491,000,000","969,000,000","522,000,000","575,000,000","-240,000,000","6,000,000",...,"239,000,000",NaN,NaN,NaN,NaN,"10,169,000,000","6,000,000","246,000,000","-240,000,000","625,000,000"
3,9/30/20,"8,771,000,000","6,708,000,000","2,063,000,000","1,254,000,000","888,000,000","366,000,000","809,000,000","-157,000,000","6,000,000",...,"331,000,000",0.320,0.270,"937,000,000","1,105,000,000","7,962,000,000","6,000,000","163,000,000","-157,000,000","718,000,000"
4,6/30/20,"6,036,000,000","4,769,000,000","1,267,000,000","940,000,000","661,000,000","279,000,000","327,000,000","-162,000,000","8,000,000",...,"104,000,000",0.112,0.100,"930,000,000","1,035,000,000","5,709,000,000","8,000,000","170,000,000","-162,000,000","320,000,000"
5,3/31/20,"5,985,000,000","4,751,000,000","1,234,000,000","951,000,000","627,000,000","324,000,000","283,000,000","-159,000,000","10,000,000",...,"16,000,000",0.018,0.016,"915,000,000","995,000,000","5,702,000,000","10,000,000","169,000,000","-159,000,000","239,000,000"
6,12/31/19,"7,384,000,000","5,993,000,000","1,391,000,000","1,044,000,000","699,000,000","345,000,000","347,000,000","-160,000,000","10,000,000",...,"105,000,000",0.116,0.112,"900,000,000","935,000,000","7,037,000,000","10,000,000","170,000,000","-160,000,000","344,000,000"
7,9/30/19,"6,303,000,000","5,112,000,000","1,191,000,000","930,000,000","596,000,000","334,000,000","261,000,000","-170,000,000","15,000,000",...,"143,000,000",0.160,0.156,"895,000,000","920,000,000","6,042,000,000","15,000,000","185,000,000","-170,000,000","361,000,000"
8,6/30/19,"6,349,676,000","5,428,630,000","921,046,000","971,159,000","647,261,000","323,898,000","-50,113,000","-161,617,000","10,362,000",...,"-408,334,000",-0.462,-0.462,"883,270,000","883,270,000","6,399,789,000","10,362,000","171,979,000","-161,617,000","-197,852,000"
9,3/31/19,"4,541,464,000","3,975,721,000","565,743,000","1,044,103,000","703,929,000","340,174,000","-478,360,000","-148,691,000","8,762,000",...,"-702,135,000",-0.820,-0.820,"864,945,000","864,945,000","5,019,824,000","8,762,000","157,453,000","-148,691,000","-487,319,000"
10,12/31/18,"7,225,873,000","5,782,973,000","1,442,900,000","1,023,749,000","667,452,000","356,297,000","419,151,000","-167,375,000","7,348,000",...,"139,483,000",0.162,0.156,"860,130,000","895,130,000","6,806,722,000","7,348,000","174,723,000","-167,375,000","406,679,000"
11,9/30/18,"6,824,413,000","5,300,748,000","1,523,665,000","1,080,724,000","729,876,000","350,848,000","442,941,000","-168,313,000","6,907,000",...,"311,516,000",0.364,0.350,"854,465,000","854,465,000","6,381,472,000","6,907,000","175,220,000","-168,313,000","446,540,000"
12,6/30/18,"4,002,231,000","3,383,301,000","618,930,000","1,136,888,000","750,759,000","386,129,000","-517,958,000","-158,518,000","5,064,000",...,"-717,539,000",-0.844,-0.844,"849,985,000","849,985,000","4,520,189,000","5,064,000","163,582,000","-158,518,000","-565,417,000"
13,3/31/18,"3,408,751,000","2,952,225,000","456,526,000","1,053,500,000","686,404,000","367,096,000","-596,974,000","-144,332,000","5,214,000",...,"-709,551,000",-0.838,-0.838,"845,730,000","845,730,000","4,005,725,000","5,214,000","149,546,000","-144,332,000","-629,476,000"
14,12/31/17,"3,288,249,000","2,849,463,000","438,786,000","1,036,927,000","682,290,000","354,637,000","-598,141,000","-140,083,000","6,280,000",...,"-675,350,000",-0.802,-0.802,"841,570,000","841,570,000","3,886,390,000","6,280,000","146,363,000","-140,083,000","-633,538,000"
15,9/30/17,"2,984,675,000","2,535,535,000","449,140,000","984,620,000","652,998,000","331,622,000","-535,480,000","-111,578,000","5,531,000",...,"-619,376,000",-0.740,-0.740,"836,470,000","836,470,000","3,520,155,000","5,531,000","117,109,000","-111,578,000","-554,339,000"
16,6/30/17,"2,789,557,000","2,122,942,000","666,615,000","907,531,000","537,757,000","369,774,000","-240,916,000","-103,656,000","4,785,000",...,"-336,397,000",-0.408,-0.408,"826,060,000","826,060,000","3,030,473,000","4,785,000","108,441,000","-103,656,000","-277,339,000"
17,3/31/17,"2,696,270,000","2,028,324,000","667,946,000","925,495,000","603,455,000","322,040,000","-257,549,000","-96,256,000","3,090,000",...,"-330,277,000",-0.408,-0.408,"810,645,000","810,645,000","2,953,819,000","3,090,000","99,346,000","-96,256,000","-272,557,000"
18,12/31/16,"2,284,631,000","1,849,353,000","435,278,000","701,976,000","456,016,000","245,960,000","-266,698,000","-62,925,000","2,179,000",...,"-121,337,000",-0.156,-0.156,"775,120,000","775,120,000","2,551,329,000","2,179,000","65,104,000","-62,925,000","-143,295,000"
19,9/30/16,"2,298,436,000","1,661,701,000","636,735,000","551,113,000","336,811,000","214,302,000","85,622,000","-43,855,000","2,858,000",...,"21,878,000",0.030,0.028,"744,955,000","784,675,000","2,212,814,000","2,858,000","46,713,000","-43,855,000","76,724,000"
20,6/30/16,"1,270,017,000","995,241,000","274,776,000","512,816,000","321,152,000","191,664,000","-238,040,000","-44,126,000","2,242,000",...,"-293,188,000",-0.418,-0.418,"699,915,000","699,915,000","1,508,057,000","2,242,000","46,368,000","-44,126,000","-243,171,000"
21,3/31/16,"1,147,048,000","894,580,000","252,468,000","500,692,000","318,210,000","182,482,000","-248,224,000","-39,374,000","1,251,000",...,"-282,267,000",-0.426,-0.426,"663,380,000","663,380,000","1,395,272,000","1,251,000","40,625,000","-39,374,000","-237,796,000"
22,12/31/15,"1,214,380,000","995,816,000","218,564,000","478,897,000","288,654,000","190,243,000","-260,333,000","-37,867,000","750,000",...,"-320,397,000",-0.488,-0.488,"655,500,000","655,500,000","1,474,713,000","750,000","38,617,000","-37,867,000","-276,732,000"
23,9/30/15,"936,789,000","705,293,000","231,496,000","415,158,000","236,367,000","178,791,000","-183,662,000","-28,981,000","327,000",...,"-229,858,000",-0.356,-0.356,"645,030,000","645,030,000","1,120,451,000","327,000","29,308,000","-28,981,000","-198,766,000"
24,6/30/15,"954,976,000","741,606,000","213,370,000","383,558,000","201,846,000","181,712,000","-170,188,000","-24,105,000","247,000",...,"-184,227,000",-0.290,-0.290,"633,445,000","633,445,000","1,125,164,000","247,000","24,352,000","-24,105,000","-156,708,000"
25,3/31/15,"939,880,000","679,807,000","260,073,000","362,519,000","195,365,000","167,154,000","-102,446,000","-26,390,000","184,000",...,"-154,181,000",-0.244,-0.244,"629,735,000","629,735,000","1,042,326,000","184,000","26,574,000","-26,390,000","-124,567,000"
26,12/31/14,"956,661,000","694,964,000","261,697,000","336,535,000","196,970,000","139,565,000","-74,838,000","-28,484,000","219,000",...,"-107,629,000",-0.172,-0.172,"627,485,000","627,485,000","1,031,499,000","219,000","28,703,000","-28,484,000","-75,207,000"
27,9/30/14,"851,804,000","599,953,000","251,851,000","290,980,000","155,107,000","135,873,000","-39,129,000","-28,762,000","300,000",...,"-74,708,000",-0.120,-0.120,"624,555,000","624,555,000","890,933,000","300,000","29,062,000","-28,762,000","-41,919,000"
28,6/30/14,"769,349,000","556,354,000","212,995,000","241,748,000","134,031,000","107,717,000","-28,753,000","-30,771,000","467,000",...,"-61,900,000",-0.100,-0.100,"621,250,000","621,250,000","798,102,000","467,000","31,238,000","-30,771,000","-29,512,000"
29,3/31/14,"620,542,000","465,414,000","155,128,000","199,095,000","117,551,000","81,544,000","-43,967,000","-11,742,000","141,000",...,"-49,800,000",-0.080,-0.080,"617,365,000","617,365,000","664,509,000","141,000","11,883,000","-11,742,000","-37,108,000"
30,12/31/13,"615,219,000","458,630,000","156,589,000","169,942,000","101,489,000","68,453,000","-13,353,000","-6,137,000","92,000",...,"-16,264,000",-0.026,-0.026,"614,010,000","614,010,000","628,572,000","92,000","6,229,000","-6,137,000","-8,677,000"
31,9/30/13,"431,346,000","328,478,000","102,868,000","133,422,000","77,071,000","56,351,000","-30,554,000","-6,424,000","68,000",...,"-38,496,000",-0.064,-0.064,"609,310,000","609,310,000","461,900,000","68,000","6,492,000","-6,424,000","-31,226,000"
32,6/30/13,"405,139,000","304,656,000","100,483,000","112,275,000","59,963,000","52,312,000","-11,792,000","-20,077,000","39,000",...,"-30,502,000",-0.052,-0.052,"590,970,000","590,970,000","416,931,000","39,000","20,116,000","-20,077,000","-10,085,000"
33,3/31/13,"561,792,000","465,472,000","96,320,000","101,904,000","47,045,000","54,859,000","-5,584,000","-108,000","10,000",...,"11,248,000",0.020,0.018,"573,560,000","621,325,000","567,376,000","10,000","118,000","-108,000","11,517,000"
34,12/31/12,"306,332,000","282,475,000","23,857,000","114,740,000","45,908,000","68,832,000","-90,883,000","59,000","85,000",...,"-89,931,000",-0.158,-0.158,"568,815,000","568,815,000","397,215,000","85,000","26,000","59,000","-90,053,000"
35,9/30/12,"50,104,000","58,865,000","-8,761,000","99,699,000","37,798,000","61,901,000","-108,460,000","-40,000","38,000",...,"-110,804,000",-0.210,-0.210,"527,780,000","527,780,000","158,564,000","38,000","78,000","-40,000","-110,610,000"
36,6/30/12,"26,653,000","21,891,000","4,762,000","110,937,000","36,083,000","74,854,000","-106,175,000","-10,000","74,000",...,"-105,603,000",-0.200,-0.200,"526,210,000","526,210,000","132,828,000","74,000","84,000","-10,000","-105,410,000"
37,3/31/12,"30,167,000","19,957,000","10,210,000","98,973,000","30,582,000","68,391,000","-88,763,000","25,000","90,000",...,"-89,873,000",-0.172,-0.172,"523,920,000","523,920,000","118,930,000","90,000","65,000","25,000","-89,749,000"
38,12/31/11,"39,375,000","31,540,000","7,835,000","88,762,000","27,557,000","61,205,000","-80,927,000","46,000","89,000",...,"-81,489,000",NaN,NaN,NaN,NaN,"120,302,000","89,000","43,000","46,000","-81,334,000"
39,9/30/11,"57,666,000","40,442,000","17,224,000","81,701,000","27,618,000","54,083,000","-64,477,000","80,000","80,000",...,"-65,078,000",-0.126,-0.126,"520,384,150","520,384,150","122,143,000","80,000",0,"80,000","-64,991,000"
40,6/30/11,"58,171,000","39,663,000","18,508,000","77,247,000","24,716,000","52,531,000","-58,739,000","46,000","46,000",...,"-58,903,000",-0.120,-0.120,"488,786,330","488,786,330","116,910,000","46,000",0,"46,000","-58,764,000"
41,3/31/11,"49,030,000","31,002,000","18,028,000","65,374,000","24,212,000","41,162,000","-47,346,000","40,000","40,000",...,"-48,941,000",-0.102,-0.102,"475,936,725","475,936,725","96,376,000","40,000",0,"40,000","-48,791,000"
42,12/31/10,"36,286,000","24,965,000","11,321,000","62,966,000","25,349,000","37,617,000","-51,645,000","63,000","63,000",...,"-51,358,000",NaN,NaN,NaN,NaN,"87,931,000","63,000",0,"63,000","-51,395,000"
43,9/30/10,"31,241,000","21,945,000","9,296,000","47,130,000","20,432,000","26,698,000","-37,834,000","-198,000","100,000",...,"-34,935,000",-0.076,-0.076,"461,353,605","461,353,605","69,075,000","100,000","298,000","-198,000","-34,554,000"
44,6/30/10,"28,405,000","22,144,000","6,261,000","37,623,000","22,207,000","15,416,000","-31,362,000","-417,000","47,000",...,"-38,517,000",-1.008,-1.008,"38,217,325","38,217,325","59,767,000","47,000","464,000","-417,000","-38,044,000"
45,3/31/10,"20,812,000","16,960,000","3,852,000","29,850,000","16,585,000","13,265,000","-25,998,000","-182,000","48,000",...,"-29,519,000",-0.070,-0.070,"389,869,155","389,869,155","46,810,000","48,000","230,000","-182,000","-29,171,000"
46,12/31/09,"18,585,000","16,804,000","1,781,000","24,706,000","16,563,000","8,143,000","-22,925,000","37,000","62,000",...,"-24,242,000",NaN,NaN,NaN,NaN,"41,510,000","62,000","25,000","37,000","-23,988,000"
47,9/30/09,"45,527,000","37,828,000","7,699,000","11,990,000","10,733,000","1,257,000","-4,291,000","34,000","52,000",...,"-4,615,000",-0.012,-0.012,"389,869,155","389,869,155","49,818,000","52,000","18,000","34,000","-4,816,000"
48,6/30/09,"26,945,000","24,844,000","2,101,000","10,188,000","8,247,000","1,941,000","-8,087,000","-1,057,000","29,000",...,"-10,867,000",-0.028,-0.028,"389,869,155","389,869,155","35,032,000","29,000","1,086,000","-1,057,000","-9,773,000"
49,3/31/09,"20,886,000","22,932,000","-2,046,000","14,548,000","6,607,000","7,941,000","-16,594,000","-1,386,000","16,000",...,"-16,016,000",-0.041,-0.041,"389,869,155","389,869,155","37,480,000","16,000","1,402,000","-1,386,000","-14,606,000"
50,12/31/08,"14,162,000","15,864,000","-1,702,000","21,522,000","9,696,000","11,826,000","-23,224,000","-1,056,000","43,000",...,"-25,498,000",NaN,NaN,NaN,NaN,"37,386,000","43,000","1,099,000","-1,056,000","-24,375,000"

pandas.core.frame.DataFrame

### 5. Create a new column of data derived from the data that you have already imported. hint: this may be a ratio or whatever transformation that you think would be useful...

### 6. Use a for loop to print individually each column in the dataframe.

### 7. Create a function that plots 2 to 3 different variables from the dataframe. The function may look something like "def plot_data(df,names, etc...). Each plot should include a legend and title.

### 8. Create a bar graph plot using the data you have imported.

### 9. On any of the graphs you have created, change the font size, axis labels, tick labels, color, linewidth, and so forth. Adjust these parameters to make the visualization aesthetically appealing.